services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  backend:
    restart: always
    build:
      context: ./backend
    container_name: backend
    # command: ["tail", "-f", "/dev/null"]
    command: sh -c "python app.py"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    ports:
      - "5003:5003"
    depends_on:
      - postgres